spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy_ong
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true

amazonProperties:
  endpointUrl:
  accessKey:
  secretKey:
  bucketName:

spring.sendgrid.api-key: 

